#!/bin/bash

echo "This script needs to install some packages as root, so please enter your password if prompted."
echo "Installing system-level packages..."

echo "Updating apt first..."
yes | sudo apt-get update

echo "Installing packages..."
if ! command -v yes | sudo apt-get install python3.12 python3.12-tk python3.12-pip python3.12-dev patchelf tar &> /dev/null
then
    echo "done"
else
    echo "Command failed, probably because Deadsnakes PPA is not installed. Please add the deadsnakes PPA to continue."
    exit 1
fi

echo "Installing python packages with pip..."
if python3 -m pip install -r requirements.txt --break-system-packages &> /dev/null; then
    echo "Required python packages installed"
else
    echo "Command failed, probably because this is running on python that comes from apt on Debian-based distros, running without --break-system-packages"
    python3 -m pip install -r requirements.txt
fi
echo "done"
